[chain]
chain_id = "tabi_9789-1"
grpc_addr = "localhost:9090"

[tx]
gas_limit = 4000000
fee_amount = "8000000000000000"
fee_denom = "atabi"

[keyring]
dir = "../../keyring-dir"
backend = "test"

[[accounts]]
name = "alice0"
mnemonic = "SET YOUR MNEMONIC"
coin_type = 60
account_index = 0
address_index = 0

[[accounts]]
name = "alice1"
mnemonic = "SET YOUR MNEMONIC"
coin_type = 60
account_index = 1
address_index = 0